### ISSUE TITLE
自定义先行发声和Overlap的比例

### ISSUE THREAD

**Issue by Reka-Currian** [shine5402/KiraOtoToolbox#27]
可以自定义方案，如，元音连续为二分之一的比例，其他为三分之一的比例

**Comment by Reka-Currian** [comment]
Can design different plans of proportion of preutterance and overlap.
eg. VCV: VV part for 1/2; others for 1/3

**Comment by shine5402** [comment]
Thanks for give me your idea here!
As it's too unflexible if I just hard-code the solution for this feature, so I may delay this until I finish #24 , which can give me enough information to tell which otos is VV part.

**Comment by shine5402** [comment]
Some sort of implemented in #18
